Repository owncloud/configreport, pull requests merged in 2018-10, with the labels that each got.

#73 Acceptance Tests Structure and 1st test related CLI
  .drone.yml
  Makefile
  tests/acceptance/.gitignore
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiConfigReport/occConfigReportReturnCode.feature
  tests/acceptance/features/bootstrap/ConfigReportContext.php
  tests/acceptance/features/bootstrap/bootstrap.php
Labels: 3 - To Review

#74 Simplify run.sh command
  Makefile
Labels: QA-Team

#75 add oracle as database backend for running tests
  .drone.yml
Labels: QA-Team

#77 Bump max-version to 11.0.0.0
  appinfo/info.xml
Labels: 3 - To Review, QA-Team
