Repository owncloud/configreport, pull requests merged in 2019-01, with the labels that each got.

#89 [stable10] Standardize CI-related scripts
  .drone.yml
  .gitignore
  Makefile
  phpunit.xml
  tests/acceptance/.gitignore
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiConfigReport/occConfigReportReturnCode.feature
  tests/acceptance/features/bootstrap/ConfigReportContext.php
  tests/acceptance/features/bootstrap/bootstrap.php
Labels: 3 - To Review, Drone, QA-Team

#91 Fix oracle unit test
  .drone.yml
  tests/unit/ReportDataCollectorTest.php
Labels: 3 - To Review

#86 [stable10] Backport of Add oc tables and details to report
  lib/Command/ConfigReport.php
  lib/ReportDataCollector.php
  tests/unit/ReportDataCollectorTest.php
Labels: 3 - To Review

#92 Add php_codesniffer to check acceptance test code style
  Makefile
  phpcs.xml
  vendor-bin/php_codesniffer/composer.json
Labels: 3 - To Review, QA-Team

#93 Install and run behat from vendor-bin
  Makefile
  tests/acceptance/config/behat.yml
  vendor-bin/behat/composer.json
Labels: 3 - To Review, QA-Team
