Repository owncloud/configreport, pull requests merged in 2020-12, with the labels that each got.

#138 [Tests-Only][CI] fix the starlark code for reduced ci after merge and sonarcloud
  .drone.star
  .gitignore
  sonar-project.properties
Labels: 4 - To release, QA-Team

#139 [Tests-Only][CI] fix sonarcloud reporting in CI
  .drone.star
  sonar-project.properties
Labels: QA-Team

#140 [tests-only] Implement latest .drone.star as at 2020-12-22
  .drone.star
  vendor-bin/behat/composer.json
  vendor-bin/php_codesniffer/composer.json
Labels: 3 - To Review, QA-Team
